

version: '3.8'
services:
  fast-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_USER=root
      - DB_PASS=root
      - DB_HOST=db
      - DB_NAME=genie
      - DB_PORT=3306
    depends_on:
      - db

    restart: always
    networks:
      - dzmouhami-network
  db:
    image: 'mysql:5.7'
    environment:
      - MYSQL_DATABASE=genie
      - MYSQL_ROOT_PASSWORD=root
    hostname: db
    ports:
      - '3306:3306'
    expose:
      - 3306
    volumes:
      - './mysql:/var/lib/mysql'
    networks:
      - dzmouhami-network
networks:
  dzmouhami-network:
    driver: bridge